
import numpy as np
import torch
from typing import Optional, Dict, Any
from transformers import TextIteratorStreamer

from ...utils import logging
from ..model_base.modeling_base import model_base
from ...inference.libshepd_inc import vlm_vit_mode
from ...inference.infer_configuration import VLM_MODEL_TYPE_NAME

logger = logging.get_logger(__name__)


def check_image_type(image_tensor, vit_mode):
	"""Check and validate the input image tensor for VLM models.

	Args:
		image_tensor: Input image tensor, should be torch.Tensor or np.ndarray
		vit_mode: VIT mode (IMAGE, VIDEO, or AUDIO)

	Returns:
		Validated image tensor as numpy array, or None if validation fails
	"""
	if type(image_tensor) != torch.Tensor and type(image_tensor) != np.ndarray:
		logger.error("VLM: the type of input images should be torch.Tensor or np.ndarray")
		return None

	if image_tensor.ndim != 4:
		logger.error("VLM: the dimension of input images should be 4")
		return None

	if isinstance(image_tensor, torch.Tensor):
		image_tensor = image_tensor.numpy().astype(np.uint8)

	IMG_N, IMG_C, IMG_H, IMG_W = \
		image_tensor.shape[0], image_tensor.shape[1], image_tensor.shape[2], image_tensor.shape[3]

	if vit_mode == vlm_vit_mode.VLM_VIT_IMAGE:
		# Image mode validation
		if IMG_C != 3:
			logger.error(
				f"VLM: vit_mode: {vit_mode}, "
				f"image mode requires 3 channels, "
				f"but current input is: {IMG_N},{IMG_C},{IMG_H},{IMG_W}")
			return None
	elif vit_mode == vlm_vit_mode.VLM_VIT_VIDEO:
		# Video mode is not supported yet
		raise NotImplementedError("VLM: video mode is not supported yet")
	elif vit_mode == vlm_vit_mode.VLM_VIT_AUDIO:
		# Audio mode is not supported yet
		raise NotImplementedError("VLM: audio mode is not supported yet")
	else:
		logger.error(f"VLM: unsupported vit mode: {vit_mode}")
		return None

	return image_tensor


class VLMForCausalLM(model_base):
	"""VLM model adapter for Ambarella hardware.

	This class provides the interface to run VLM models on Ambarella chips,
	supporting image, video, and audio modalities through the VLM (Vision Language Model)
	framework.
	"""

	def __init__(
		self,
		pretrained_model_path: str,
		device_ip: str = None,
		device_port: int = None,
		log_level: Optional[int] = None,
	):
		self.model_type = VLM_MODEL_TYPE_NAME
		super().__init__(
			pretrained_model_path = pretrained_model_path,
			device_ip = device_ip,
			device_port = device_port,
			log_level = log_level,
			model_type = self.model_type)

	@classmethod
	def from_pretrained(
		cls,
		pretrained_model_path: Optional[str] = None,
		device_ip: Optional[str] = None,
		device_port: Optional[int] = None,
		log_level: Optional[int] = None,
		**kwargs,
	):
		r"""Load a pretrained VLM model.

		Args:
			pretrained_model_path (`str`, *optional*):
				Indices the model path which generated by Ambarella tool.
			device_ip (`str`, *optional*):
				It's an extended configuration for Ambarella chips to index the IP address if enable RPC mode.
			device_port (`int`, *optional*):
				It's an extended configuration for Ambarella chips to index the port number if enable RPC mode.
			log_level (`int`, *optional*):
				It's an extended configuration for Ambarella chips to index the log level for Shepherd library.
		"""
		if kwargs:
			logger.warning(f"{cls.__name__}: unsupported kwargs: {kwargs}")
		return cls(pretrained_model_path, device_ip, device_port, log_level)

	def __del__(self):
		super().__del__()

	def tokenizer_image_token(
		self,
		img_tensor: torch.Tensor = None,
		vit_mode: Optional[int] = None,
		user_id: Optional[list] = None
	):
		r"""Run vision tower model to get image embedding.

		This API will run vision tower model to get image embedding for Shepherd library.
		Users should use model.encode API to get text tokens instead of using tokenizer from Transformers
		because some related state for image was maintained by Shepherd.

		Args:
			img_tensor (`torch.Tensor`):
				Indices the input image data.
			vit_mode (`int`, *optional*):
				It's an extended configuration for Ambarella chips to index the vit mode for vision tower model.
				0: image; 1: video; 2: audio. Default is image mode.
			user_id (`list`, *optional*):
				It's an extended configuration for Ambarella chips to index the user ID for current inference.
				Users need specify this parameters if enable multi user.
		"""
		if img_tensor is None:
			logger.error("tokenizer_image_token: input with img_tensor should not None")
			return None

		vmode = vit_mode if vit_mode is not None else vlm_vit_mode.VLM_VIT_IMAGE
		prompt = None

		img_tensor = check_image_type(img_tensor, vmode)
		if img_tensor is None:
			raise ValueError("check_image_type fail")

		user_ctx = self.multi_user_get(user_id)

		num_images = img_tensor.shape[0]
		self.infer.infer_user_preprocess(
			self.model_handle, user_ctx.handle, self.model_type, vmode,
			prompt, img_tensor, num_images)
		return None

	def tokenizer_text_image_token(
		self,
		prompt: str = None,
		img_tensor: torch.Tensor = None,
		vit_mode: Optional[int] = None,
		user_id: Optional[list] = None,
	):
		r"""Encode text and image tokens together.

		This API will apply default system prompt for input text by Shepherd library,
		run vision tower model to get image embedding and then return the encoded token list which
		includes text tokens and image tokens.

		Args:
			prompt (`str`):
				Indices the input prompt text.
			img_tensor (`torch.Tensor`):
				Indices the input image data.
			vit_mode (`int`, *optional*):
				It's an extended configuration for Ambarella chips to index the vit mode for vision tower model.
				0: image; 1: video; 2: audio. Default is image mode.
			user_id (`list`, *optional*):
				It's an extended configuration for Ambarella chips to index the user ID for current inference.
				Users need specify this parameters if enable multi user.

		Returns (`torch.Tensor`):
			return the merged token list include text tokens and image tokens
		"""
		if prompt is None or img_tensor is None:
			logger.error("tokenizer_text_image_token: input with prompt and img_tensor should not None")
			return None

		vmode = vit_mode if vit_mode is not None else vlm_vit_mode.VLM_VIT_IMAGE
		img_tensor = check_image_type(img_tensor, vmode)
		if img_tensor is None:
			raise ValueError("check_image_type fail")

		user_ctx = self.multi_user_get(user_id)

		num_images = img_tensor.shape[0]
		input_ids = self.infer.infer_user_preprocess(
			self.model_handle, user_ctx.handle, self.model_type, vmode,
			prompt, img_tensor, num_images)
		return self.output_ids_cvt(input_ids)

	def generate(
		self,
		input_ids: Optional[torch.Tensor] = None,
		position: Optional[list] = None,
		user_id: Optional[list] = None,
		past_key_values: Optional[bool] = None,
		streamer: Optional[TextIteratorStreamer] = None,
		**kwargs: Dict,
	):
		r"""Generate text response for given input.

		Args:
			input_ids (`torch.Tensor`):
				Indices the input data which include input text.
			position (`list`, *optional*):
				Indices to get of position of current conversation, like position=[], default is None.
			user_id (`list`, *optional*):
				It's an extended configuration for Ambarella chips to index the user ID for current inference.
				Users need specify this parameters if enable multi user.
			past_key_values (`bool`, *optional*):
				Indices the past conversation can be used for current inference.
			streamer (`TextIteratorStreamer`, *optional*):
				Streamer object that will be used to stream the generated sequences. Generated tokens are passed
				through `streamer.put(token_ids)` and the streamer is responsible for any further processing.
			kwargs (additional keyword arguments, *optional*):
				Compared to transformers, we currently only support some of the commonly used parameters as below:
					`do_sample`, `top_p`, `top_k`, and `temperature` are added to enable different sample methods
					with logits. `do_sample=None` will choose a hardware sample by default, `do_sample=False/True`
					will choose a different sample according to other configs like `top_p`, `top_k`.

					`max_length`, `max_new_tokens` are added to change the default max sequence length.

		Returns:
			`numpy.array`: the array of output token id

		Example:

		.. code-block:: python

			import numpy as np

			from transformers import AutoTokenizer
			from transformers_amba_ext import VLMForCausalLM

			# Please replace this path with your actual model artifacts directory
			model_path = "/path/to/your/vlm_model"
			tokenizer = AutoTokenizer.from_pretrained(model_path, local_files_only=True)
			model = VLMForCausalLM.from_pretrained(model_path)

			# Load preprocessed image binary
			# image_tensor shape should be (N, C, H, W), e.g., (1, 3, 448, 448)
			image_tensor = np.fromfile("test_image.bin", dtype=np.uint8)
			image_tensor = image_tensor.reshape(-1, 3, 448, 448)

			# Prepare text prompt
			question = "<image>\nPlease describe this image in detail."

			# Below API will apply system prompt automatically by shepherd library
			input_ids = model.tokenizer_text_image_token(question, image_tensor)

			# Generate response
			output_ids = model.generate(
				input_ids,
				do_sample=None,
				temperature=0,
				max_new_tokens=512,
			)
			text_outputs = tokenizer.batch_decode(output_ids, skip_special_tokens=True)
			print(text_outputs[0])
		"""
		do_sample = kwargs.get("do_sample")

		input = self.input_ids_cvt(input_ids)
		if do_sample is not None:
			output = super().generate_logits_until(
				input_ids = input,
				position = position,
				user_id = user_id,
				past_key_values = past_key_values,
				streamer = streamer,
				kwargs = kwargs)
		else:
			output = super().generate_ids_until(
				input_ids = input,
				position = position,
				user_id = user_id,
				past_key_values = past_key_values,
				streamer = streamer,
				kwargs = kwargs)
		return self.output_ids_cvt(output)

	def to(self, device):
		r"""Bypass device placement (model runs on Ambarella hardware)."""
		return self
