from typing import Optional, Dict
from ..llama.modeling_llama import LlamaForCausalLM
from ...utils import logging

logger = logging.get_logger(__name__)

class Qwen2ForCausalLM(LlamaForCausalLM):
	@classmethod
	def from_pretrained(
		cls,
		pretrained_model_path: Optional[str] = None,
		device_ip: Optional[str] = None,
		device_port: Optional[int] = None,
		log_level: Optional[int] = None,
		is_embed_model: Optional[bool] = None,
		**kwargs,
	):
		r"""
		Args:
			pretrained_model_path (`str`, *optional*):
				Indices the model path which generated by Ambarella tool.
			device_ip (`str`, *optional*):
				It's an extended configuration for Ambarella chips to index the IP address if enable RPC mode.
			device_port (`int`, *optional*):
				It's an extended configuration for Ambarella chips to index the port number if enable RPC mode.
			log_level (`int`, *optional*):
				It's an extended configuration for Ambarella chips to index the log level for Shepherd library.
			is_embed_model (`bool`, *optional*):
				It's an extended configuration for Ambarella chips to index the embedding model for Shepherd library.
		"""
		if kwargs:
			logger.warning(f"{cls.__name__}: unsupported kwargs: {kwargs}")
		return cls(pretrained_model_path, device_ip, device_port, log_level, is_embed_model)